In [25]:
import pandas as pd
loan_df=pd.read_csv("Loan.csv")
loan_df

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,2018-01-01,45,39948,617,Employed,Master,22,13152,48,Married,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,2018-01-02,38,39709,628,Employed,Associate,15,26045,48,Single,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,2018-01-03,47,40724,570,Employed,Bachelor,26,17627,36,Married,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,2018-01-04,58,69084,545,Employed,High School,34,37898,96,Single,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,2018-01-05,37,103264,594,Employed,Associate,17,9184,36,Married,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179141,0.070210,1,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2072-09-29,44,30180,587,Employed,High School,19,24521,36,Married,...,2515.000000,0.826217,1,55327,0.216021,0.195574,905.767712,0.627741,0,55.0
19996,2072-09-30,56,49246,567,Employed,Associate,33,25818,36,Married,...,4103.833333,0.816618,3,64002,0.227318,0.199168,958.395633,0.334418,0,54.0
19997,2072-10-01,44,48958,645,Employed,Bachelor,20,37033,72,Married,...,4079.833333,0.887216,3,103663,0.229533,0.226766,945.427454,0.357227,0,45.0
19998,2072-10-02,60,41025,560,Employed,High School,36,14760,72,Married,...,3418.750000,0.843787,5,10600,0.249760,0.264873,411.168284,0.408678,0,59.0
19999,2072-10-03,20,53227,574,Employed,Associate,0,32055,48,Married,...,4435.583333,0.853801,5,41372,0.240055,0.242693,1049.830407,0.298006,0,59.0

# selecting relevent coloumns based on EDA

In [26]:
df=loan_df.copy()
selected_columns=[
    'Age','CreditScore','EmploymentStatus','EducationLevel','LoanAmount',
    'LoanDuration','CreditCardUtilizationRate','BankruptcyHistory','PreviousLoanDefaults',
    'LengthOfCreditHistory','MonthlyIncome','NetWorth','InterestRate','RiskScore','LoanApproved'
]
df=df[selected_columns]
df.sample(10)

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
9380,39,583,Unemployed,Associate,8962,60,0.097136,0,1,16,3549.416667,9727,0.225656,61.0,0
6521,39,632,Employed,High School,26048,48,0.132862,0,0,10,2407.666667,85522,0.191816,48.0,0
10119,26,535,Employed,Associate,15216,24,0.397951,0,0,28,1419.750000,10234,0.229446,54.0,0
17799,31,579,Employed,Associate,30909,24,0.481246,0,0,5,2136.666667,83125,0.215159,61.0,0
5702,40,623,Employed,Associate,15099,36,0.407077,1,0,19,4033.666667,3461,0.213049,61.0,0
16501,51,626,Employed,Bachelor,29673,72,0.410991,0,0,26,9254.583333,7320,0.211527,37.6,1
11596,20,540,Employed,Master,32468,60,0.233271,0,0,29,4543.250000,82149,0.278115,54.0,0
12287,22,568,Employed,High School,24864,24,0.326923,0,0,1,4873.666667,75608,0.198489,60.0,0
15238,33,534,Employed,Associate,17964,120,0.042307,0,0,17,3353.416667,7905,0.308271,56.0,0
3226,29,592,Employed,Bachelor,14867,36,0.321173,0,0,17,1768.916667,155500,0.244640,50.0,0

In [27]:
df['EmploymentStatus']=df['EmploymentStatus'].map({'Unemployed':0,'Self-Employed':1,'Employed':2})
df['EducationLevel']=df['EducationLevel'].map({'High School':0,'Associate':1,'Bachelor':2,'Master':3,'Doctorate':4})
df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
0,45,617,2,3,13152,48,0.354418,0,0,9,3329.000000,126928,0.227590,49.0,0
1,38,628,2,1,26045,48,0.087827,0,0,9,3309.083333,43609,0.201077,52.0,0
2,47,570,2,2,17627,36,0.137414,0,0,22,3393.666667,5205,0.212548,52.0,0
3,58,545,2,0,37898,96,0.267587,0,0,10,5757.000000,99452,0.300911,54.0,0
4,37,594,2,1,9184,36,0.320535,0,0,27,8605.333333,227019,0.175990,36.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,44,587,2,0,24521,36,0.101288,0,0,7,2515.000000,55327,0.195574,55.0,0
19996,56,567,2,1,25818,36,0.471818,0,0,28,4103.833333,64002,0.199168,54.0,0
19997,44,645,2,2,37033,72,0.216596,0,0,8,4079.833333,103663,0.226766,45.0,0
19998,60,560,2,0,14760,72,0.364758,0,0,13,3418.750000,10600,0.264873,59.0,0
19999,20,574,2,1,32055,48,0.536411,0,0,14,4435.583333,41372,0.242693,59.0,0

 # Handling Skewness using log

In [28]:
Skewness = df.skew()
sorted_skewness=Skewness.sort_values(ascending=True)
print(sorted_skewness)

EmploymentStatus            -2.455244
CreditScore                 -0.596727
RiskScore                   -0.162062
LengthOfCreditHistory        0.002989
Age                          0.185964
EducationLevel               0.273155
InterestRate                 0.485491
CreditCardUtilizationRate    0.601131
LoanDuration                 0.651330
LoanApproved                 1.224086
LoanAmount                   1.833688
MonthlyIncome                1.992929
PreviousLoanDefaults         2.665941
BankruptcyHistory            4.017672
NetWorth                     5.599844
dtype: float64

In [29]:
import numpy as np
features_to_lof1p=['LoanAmount','MonthlyIncome','NetWorth']
df[features_to_lof1p]=df[features_to_lof1p].apply(np.log1p)
df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
0,45,617,2,3,9.484405,48,0.354418,0,0,9,8.110728,11.751383,0.227590,49.0,0
1,38,628,2,1,10.167619,48,0.087827,0,0,9,8.104729,10.683042,0.201077,52.0,0
2,47,570,2,2,9.777244,36,0.137414,0,0,22,8.129961,8.557567,0.212548,52.0,0
3,58,545,2,0,10.542680,96,0.267587,0,0,10,8.658345,11.507440,0.300911,54.0,0
4,37,594,2,1,9.125327,36,0.320535,0,0,27,9.060254,12.332793,0.175990,36.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,44,587,2,0,10.107326,36,0.101288,0,0,7,7.830426,10.921034,0.195574,55.0,0
19996,56,567,2,1,10.158866,36,0.471818,0,0,28,8.319920,11.066685,0.199168,54.0,0
19997,44,645,2,2,10.519592,72,0.216596,0,0,8,8.314056,11.548910,0.226766,45.0,0
19998,60,560,2,0,9.599744,72,0.364758,0,0,13,8.137323,9.268704,0.264873,59.0,0
19999,20,574,2,1,10.375240,48,0.536411,0,0,14,8.397640,10.630384,0.242693,59.0,0

# scaling

In [30]:
from sklearn.preprocessing import StandardScaler
#Create a copy of the original data for comparison
columns_of_standize=['Age', 'CreditScore', 'LoanAmount', 'LoanDuration',
'CreditCardUtilizationRate', 'LengthOfCreditHistory',
'MonthlyIncome', 'NetWorth', 'InterestRate']

#Initialize the StandardScaler
scaler=StandardScaler()

#Apply the scaler only to the numeric columns
df[columns_of_standize]=scaler.fit_transform(df[columns_of_standize])
df.head()

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
0,0.451489,0.890021,2,3,-1.014008,-0.245578,0.425792,0,0,-0.711630,-0.324366,1.020941,-0.272968,49.0,0
1,-0.150795,1.105724,2,1,0.343015,-0.245578,-1.242602,0,0,-0.711630,-0.334247,0.287206,-0.901165,52.0,0
2,0.623571,-0.031618,2,2,-0.432362,-0.732113,-0.932273,0,0,0.841287,-0.292687,-1.172566,-0.629370,52.0,0
3,1.570017,-0.521852,2,0,1.087972,1.700559,-0.117617,0,0,-0.592175,0.577602,0.853401,1.464331,54.0,0
4,-0.236835,0.439006,2,1,-1.727221,-0.732113,0.213746,0,0,1.438563,1.239575,1.420252,-1.495584,36.0,1

In [31]:
df.shape

(20000, 15)

In [32]:
def remove_outliers_iqr(df,exclude_columns):
    # Loop through numeric columns
    for column in df.select_dtypes(include=['number']):
      if column in exclude_columns:
        continue #skip excluded columns

      Q1=df[column].quantile(0.25)
      Q3=df[column].quantile(0.75)
      IQR=Q3-Q1

      #define outlier bounds
      lower_bound=Q1-1.5*IQR
      upper_bound=Q3+1.5*IQR

      #filter out the outliers
      df=df[(df[column]>=lower_bound) & (df[column]<=upper_bound)]

    return df

#remove outliers
final_df=remove_outliers_iqr(df,columns_of_standize)

#print shapes of the data before amd after removing outliers
print('shape of data before removing outliers:',df.shape)
print('shape of data after removing outliers:',final_df.shape)
print('number of outliers removed :',df.shape[0]-final_df.shape[0])

shape of data before removing outliers: (20000, 15)
shape of data after removing outliers: (14485, 15)
number of outliers removed : 5515

In [33]:
x=final_df.drop(['RiskScore','LoanApproved'],axis=1)
y=final_df[['RiskScore']]

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

print('Shape of Training Features',x_train.shape)
print('Shape of Testing Features',x_test.shape)
print('Shape of Traing Target',y_train.shape)
print('Shape of Testing Target',y_test.shape)

Shape of Training Features (11588, 13)
Shape of Testing Features (2897, 13)
Shape of Traing Target (11588, 1)
Shape of Testing Target (2897, 1)

In [35]:
pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from lightgbm) (1.15.2)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 18.9 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
from lightgbm import LGBMRegressor
model=LGBMRegressor()
model.fit(x_train,y_train)

LGBMRegressor()

In [39]:
import pickle
with open('regresseion_model.pkl','wb') as file:
    pickle.dump(model,file)

In [40]:
with open('scaler.pkl','wb') as file:
    pickle.dump(model,file)